name       : urlscan
version    : 0.8.3
release    : 1
source     :
    - https://github.com/firecat53/urlscan/archive/0.8.3.tar.gz : 4e6bffcb762fc0406f5932a7a27b5d624e6f1b0bd2c6b785573b911b86c73486
license    : GPL-2.0
component  : network.mail
summary    : Mutt and terminal url selector (similar to urlview)
description: |
    Urlscan is a small program that is designed to integrate with the "mutt" mailreader to allow you to easily launch a Web browser for URLs contained in email messages. It is a replacement for the "urlview" program.
builddeps  :
    - pkgconfig(python-3.5)
    - python3-urwid
    - python-setuptools
build      : |
    %python3_setup
install    : |
    %python3_install
