name       : urlscan
version    : 0.8.5
release    : 2
source     :
    - https://github.com/firecat53/urlscan/archive/0.8.5.tar.gz : bd484df375af14ee2c9801850d71594b0471f8ee199c01a0bfd14ef8486b3c3e
license    : GPL-2.0
component  : network.mail
summary    : Mutt and terminal url selector (similar to urlview)
description: |
    Urlscan is a small program that is designed to integrate with the "mutt" mailreader to allow you to easily launch a Web browser for URLs contained in email messages. It is a replacement for the "urlview" program.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python3-urwid
build      : |
    %python3_setup
install    : |
    %python3_install
