name       : urlscan
version    : 0.9.4
release    : 6
source     :
    - https://github.com/firecat53/urlscan/archive/0.9.4.tar.gz : fc76c3c8a852f1fbdde69faa336184b7f060b33e8e4573d6ffa8790ed6f429b6
license    : GPL-2.0-or-later
component  : network.mail
summary    : Mutt and terminal url selector (similar to urlview)
description: |
    Urlscan is a small program that is designed to integrate with the "mutt" mailreader to allow you to easily launch a Web browser for URLs contained in email messages. It is a replacement for the "urlview" program.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - python3-urwid
build      : |
    %python3_setup
install    : |
    %python3_install
